name: CMake on a single platform

on:
  push:
    branches: [ "main", "cmake_libs_if_for" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Print message"
      run: echo "Hello world"
    - run: echo "I am an engineer"
    - run: printenv
    - run: cat /etc/os-release

